<a href="https://colab.research.google.com/github/juansan0098-afk/estructuras_numpy_pandas/blob/main/2_1_Repositorio_en_plataforma_Git_que_demuestre_el_aprovechamiento_de_estructuras_multidimensionales_bajo_NumPy_y_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
# Estructuras de Datos con NumPy y Pandas #

# Een este cuaderno demuestra la creación, manipulación y aplicación de estructuras de datos
# vectoriales y multidimensionales usando NumPy y pandas.

# Incluye ejemplos prácticos y casos de aplicación para procesamiento de datos en memoria.



In [14]:
import numpy as np

vector = np.array([10, 20, 30, 40, 50])
print("Vector NumPy:", vector)
print("Suma de elementos:", np.sum(vector))
print("Media:", np.mean(vector))
print("Máximo:", np.max(vector))

matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("\nMatriz NumPy:\n", matriz)
print("Transpuesta:\n", matriz.T)
print("Producto punto:\n", np.dot(matriz, matriz))


Vector NumPy: [10 20 30 40 50]
Suma de elementos: 150
Media: 30.0
Máximo: 50

Matriz NumPy:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpuesta:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Producto punto:
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [15]:
import pandas as pd

serie = pd.Series([100, 200, 300], index=["A", "B", "C"])
print("Serie Pandas:\n", serie)

data = {
    "Nombre": ["Ana", "Luis", "María", "Pedro"],
    "Edad": [23, 25, 22, 24],
    "Promedio": [9.1, 8.7, 9.5, 8.9]
}
df = pd.DataFrame(data)
print("\nDataFrame Pandas:\n", df)

print("\nPromedio de edades:", df["Edad"].mean())
print("\nOrdenado por Promedio:\n", df.sort_values("Promedio", ascending=False))
print("\nAlumnos con promedio >= 9:\n", df[df["Promedio"] >= 9])


Serie Pandas:
 A    100
B    200
C    300
dtype: int64

DataFrame Pandas:
   Nombre  Edad  Promedio
0    Ana    23       9.1
1   Luis    25       8.7
2  María    22       9.5
3  Pedro    24       8.9

Promedio de edades: 23.5

Ordenado por Promedio:
   Nombre  Edad  Promedio
2  María    22       9.5
0    Ana    23       9.1
3  Pedro    24       8.9
1   Luis    25       8.7

Alumnos con promedio >= 9:
   Nombre  Edad  Promedio
0    Ana    23       9.1
2  María    22       9.5


In [16]:
sensores = np.random.randint(0, 100, size=(5, 3))
print("Datos de sensores (NumPy):\n", sensores)

ventas = pd.DataFrame({
    "Producto": ["A", "B", "C", "A", "B", "C"],
    "Cantidad": [10, 20, 15, 12, 18, 22],
    "Precio": [100, 200, 150, 100, 200, 150]
})
ventas["Total"] = ventas["Cantidad"] * ventas["Precio"]
print("\nVentas (Pandas):\n", ventas)
print("\nTotal vendido por producto:\n", ventas.groupby("Producto")["Total"].sum())


Datos de sensores (NumPy):
 [[39 59 64]
 [63  2  1]
 [45 19 69]
 [38 79 33]
 [11 80 89]]

Ventas (Pandas):
   Producto  Cantidad  Precio  Total
0        A        10     100   1000
1        B        20     200   4000
2        C        15     150   2250
3        A        12     100   1200
4        B        18     200   3600
5        C        22     150   3300

Total vendido por producto:
 Producto
A    2200
B    7600
C    5550
Name: Total, dtype: int64


In [17]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
